Conceive da 'equipe_LuLu'
MatheusPinto/PI_IFSC_2023_02 pull request #3
Opened 2023-09-07 00:24 UTC by LucasAVasco

Alunos: Lucas de Amorim Vasco & Lucas Martins Wollinger

2023-09-19 21:22 UTC, MatheusPinto commented on equipe_LuLu/conceive/README.md
> +Enquanto pensávamos mais profundamente em uma proposta de projeto, encontramos uma carcaça de um robô no LPAE. Era uma versão do Wall-e (do filme “WALL-E”) impressa em uma impressora 3D (a base de pl
Pense que esse projeto deve ser visualizado por pessoas fora da instituição (ou mesmo por pessoas da instituição que não façam parte do curso). Dessa forma, explique o que é o LPAE.
Também, coloque o texto na terceira pessoa, pois se trata de um documento técnico.

2023-09-19 21:24 UTC, MatheusPinto commented on equipe_LuLu/conceive/README.md
> +Assim, a intenção desse projeto é conceber, desenvolver, implementar e operar um robô Wall-e autônomo e no modo teleoperado. Ele deve ser gerenciável remotamente, permitindo selecionar os modos de op
"operar um robô Wall-e autônomo e no modo teleoperado" é muito vago.
Vocês devem indicar o que o robô deve apresentar, quais suas funções (o que o "produto" que você vai vender faz?)

2023-09-19 21:27 UTC, MatheusPinto commented on equipe_LuLu/conceive/README.md
> +### Objetivos:
Será que esse é o objetivo do projeto?
Ou o objetivo é "recolher lixo a partir do pedido de pessoas em um ambiente fechado".
Aqui vocês estão apresentando as funcionalidades do robô e não objetivo do produto.

2023-09-19 21:35 UTC, MatheusPinto requested changes
Verificar comentários nos commits.
Notas nos critérios de avaliação:
1 - 10
2 - 7
3 - 10
4 - 10
5 - 7
6 - 7
7 - 7

2023-09-26 21:20 UTC, LucasAVasco commented on equipe_LuLu/conceive/README.md
> +Enquanto pensávamos mais profundamente em uma proposta de projeto, encontramos uma carcaça de um robô no LPAE. Era uma versão do Wall-e (do filme “WALL-E”) impressa em uma impressora 3D (a base de pl
Explicamos o que é o LPAE e que ele pertence ao IFSC. Também mudamos para terceira pessoa.

2023-09-26 21:22 UTC, LucasAVasco commented on equipe_LuLu/conceive/README.md
> +Assim, a intenção desse projeto é conceber, desenvolver, implementar e operar um robô Wall-e autônomo e no modo teleoperado. Ele deve ser gerenciável remotamente, permitindo selecionar os modos de op
Adicionamos a descrição de como deve operar. Recomendo olhar o diagrama de caso de uso que foi adicionado.

2023-09-26 21:25 UTC, LucasAVasco commented on equipe_LuLu/conceive/README.md
> +### Objetivos:
Agora, há a descrição do objetivo do produto no parágrafo anterior a esse.

2023-10-11 16:59 UTC, MatheusPinto commented
Notas nos critérios de avaliação:
1 - 10
2 - 10
3 - 10
4 - 10
5 - 10
6 - 10
7 - 10

2023-10-11 16:59 UTC, merged